# Generated by Django 4.2.29 on 2026-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_alter_historicalnote_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnote',
            name='importance',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='note',
            name='importance',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
