# Generated by Django 4.2.26 on 2026-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_migrate_importance_to_normal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='drive_modified',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='drive_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='drive_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='drive_modified',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='drive_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='drive_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
