# Generated by Django 4.2.26 on 2026-06-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_historicalnote_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnote',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
        migrations.AddField(
            model_name='note',
            name='ai_context',
            field=models.CharField(choices=[('auto', 'Auto'), ('always', 'Always'), ('never', 'Never')], default='auto', help_text='AI context inclusion: auto (selector decides), always, or never', max_length=6),
        ),
    ]
