# Generated by Django 4.2.26 on 2025-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outlines", "0013_bullets_under_headings"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlineitem",
            name="quote",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="outline",
            name="category",
            field=models.CharField(
                choices=[
                    ("analysis", "Analysis"),
                    ("drafting", "Drafting"),
                    ("interview", "Interview"),
                    ("issue", "Issue"),
                    ("note", "Note"),
                ],
                default="note",
                max_length=20,
            ),
        ),
    ]
