# Generated by Django 4.2.29 on 2026-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_historicaltask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=4),
        ),
    ]
