# Generated by Django 4.2.26 on 2025-11-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_dash_check",
            field=models.DateField(blank=True, null=True),
        ),
    ]
