# Generated by Django 4.2.29 on 2026-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_perm_research_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color_scheme',
            field=models.CharField(choices=[('classic', 'Classic'), ('blue', 'Blue'), ('purple', 'Purple'), ('teal', 'Teal')], default='classic', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='color_scheme',
            field=models.CharField(choices=[('classic', 'Classic'), ('blue', 'Blue'), ('purple', 'Purple'), ('teal', 'Teal')], default='classic', max_length=10),
        ),
    ]
