exclude: .*migrations\/.*

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check
        args: [--fix, --unsafe-fixes]
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 9112cb64851c95a7802358af285d21ad8b7f6437  # frozen: v1.36.4
    hooks:
      - id: djlint-django
        language_version: python3.13
        args: [ --profile, django ]
        exclude: "templates/emails/"
      - id: djlint-reformat-django
        files: "\\.html"
        language_version: python3.13
        args: [ --profile, django ]
        exclude: "templates/emails/"
