# Generated by Django 4.2.29 on 2026-07-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_created_at_contact_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contact',
            name='app_contact_client__ed2592_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='client_status',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='client_status',
        ),
    ]
