# Generated by Django 4.2.29 on 2026-04-17 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0011_add_importance_to_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalintake',
            name='importance',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='intake',
            name='importance',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
