# Generated by Django 4.2.26 on 2026-01-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0031_add_conversation_is_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmessage",
            name="verified_citations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="verified_citations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
