# Generated by Django 4.2.26 on 2026-01-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0028_group_created_at_group_created_by_group_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("case", "0032_add_verified_citations_to_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCaseLaw",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("citation", models.CharField(max_length=255)),
                ("case_name", models.CharField(max_length=500)),
                ("court", models.CharField(max_length=255)),
                ("court_id", models.CharField(blank=True, max_length=50)),
                ("date_filed", models.DateField(blank=True, null=True)),
                ("docket_number", models.CharField(blank=True, max_length=255)),
                ("cluster_id", models.IntegerField(blank=True, null=True)),
                ("opinion_id", models.IntegerField(blank=True, null=True)),
                ("courtlistener_url", models.URLField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("html", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="matters.matter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical case law",
                "verbose_name_plural": "historical case laws",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CaseLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("citation", models.CharField(max_length=255)),
                ("case_name", models.CharField(max_length=500)),
                ("court", models.CharField(max_length=255)),
                ("court_id", models.CharField(blank=True, max_length=50)),
                ("date_filed", models.DateField(blank=True, null=True)),
                ("docket_number", models.CharField(blank=True, max_length=255)),
                ("cluster_id", models.IntegerField(blank=True, null=True)),
                ("opinion_id", models.IntegerField(blank=True, null=True)),
                ("courtlistener_url", models.URLField(blank=True, max_length=500)),
                ("text", models.TextField()),
                ("html", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "labels",
                    models.ManyToManyField(
                        blank=True, related_name="case_laws", to="case.label"
                    ),
                ),
                (
                    "matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_laws",
                        to="matters.matter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_case_law",
                "ordering": ["-date_filed", "case_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="caselaw",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cluster_id__isnull", False)),
                fields=("matter", "cluster_id"),
                name="unique_case_per_matter",
            ),
        ),
    ]
