# Generated by Django 4.2.29 on 2026-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0066_highlight_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus', 'Claude Opus 4.8'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalconversation',
            name='llm',
            field=models.CharField(choices=[('claude-opus', 'Claude Opus 4.8'), ('gemini-flash', 'Gemini 2.5 Flash'), ('gemini-pro-latest', 'Gemini Pro (Latest)')], default='gemini-pro-latest', max_length=20),
        ),
    ]
