# Generated by Django 4.2.29 on 2026-06-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0017_invoice_show_comp_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_method',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CARD', 'Card'), ('TRUST', 'Trust'), ('WIRE', 'Wire')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CHECK', 'Check'), ('CARD', 'Card'), ('TRUST', 'Trust'), ('WIRE', 'Wire')], max_length=10),
        ),
    ]
