# Generated by Django 4.2.29 on 2026-06-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_created_at_contact_created_by_and_more'),
        ('invoicing', '0023_alter_invoicetransmission_cc_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalcredit',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.contact'),
        ),
    ]
