# Generated by Django 4.2.29 on 2026-06-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0036_backfill_deferred_fees'),
        ('invoicing', '0025_backfill_payment_credit_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matters.matter'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matters.matter'),
        ),
    ]
