# Generated by Django 4.2.29 on 2026-06-24 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_event_type_and_location_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingGoogleDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('calendar_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'app_calendar_pending_deletion',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='google_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='google_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
