# Generated by Django 4.2.26 on 2025-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0009_rename_highlight_title_to_slug"),
        ("matters", "0023_practicearea_and_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fact",
            name="citations",
        ),
        migrations.AddField(
            model_name="fact",
            name="case",
            field=models.ManyToManyField(
                blank=True, related_name="facts", to="case.document"
            ),
        ),
        migrations.AddField(
            model_name="fact",
            name="highlights",
            field=models.ManyToManyField(
                blank=True, related_name="facts", to="case.highlight"
            ),
        ),
    ]
