# Generated by Django 4.2.26 on 2026-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0033_historicalmatter_billing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='drive_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='drive_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
