# Generated by Django 4.2.29 on 2026-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0034_historicalmatter_drive_folder_matter_drive_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatter',
            name='deferred_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matter',
            name='deferred_fees',
            field=models.BooleanField(default=False),
        ),
    ]
