# Generated by Django 4.2.29 on 2026-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0036_backfill_deferred_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmatter',
            name='work_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='work_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
