# Generated by Django 4.2.29 on 2026-07-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0037_alter_historicalmatter_work_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='matter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='matters.matter'),
        ),
    ]
