# Generated by Django 4.2.29 on 2026-07-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0039_rebase_matter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='matters.matter'),
        ),
    ]
