# Generated by Django 4.2.29 on 2026-07-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0040_alter_group_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
