# Generated by Django 4.2.22 on 2025-11-22 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_rename_term_to_focus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="urgent",
        ),
    ]
