# Generated by Django 4.2.22 on 2025-11-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0006_remove_task_urgent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="focus",
        ),
    ]
