# Generated by Django 4.2.26 on 2026-06-08 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_token', models.TextField(blank=True, null=True)),
                ('unmatched_folders', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_drive_sync_state',
            },
        ),
    ]
